# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1887, 931)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 260, 291, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GridLayout_Table = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GridLayout_Table.setContentsMargins(0, 0, 0, 0)
        self.GridLayout_Table.setObjectName("GridLayout_Table")
        self.tableWidget_Sample_Information = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Sample_Information.sizePolicy().hasHeightForWidth())
        self.tableWidget_Sample_Information.setSizePolicy(sizePolicy)
        self.tableWidget_Sample_Information.setObjectName("tableWidget_Sample_Information")
        self.tableWidget_Sample_Information.setColumnCount(0)
        self.tableWidget_Sample_Information.setRowCount(0)
        self.GridLayout_Table.addWidget(self.tableWidget_Sample_Information, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 260, 1571, 581))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.GridLayout_Figure = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.GridLayout_Figure.setContentsMargins(0, 0, 0, 0)
        self.GridLayout_Figure.setObjectName("GridLayout_Figure")
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.GridLayout_Figure.addWidget(self.widget, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 1871, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_Sample_Information = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_Sample_Information.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Sample_Information.sizePolicy().hasHeightForWidth())
        self.toolButton_Sample_Information.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_Sample_Information.setFont(font)
        self.toolButton_Sample_Information.setObjectName("toolButton_Sample_Information")
        self.gridLayout.addWidget(self.toolButton_Sample_Information, 0, 0, 1, 1)
        self.Label_Sample_Now = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Sample_Now.sizePolicy().hasHeightForWidth())
        self.Label_Sample_Now.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Sample_Now.setFont(font)
        self.Label_Sample_Now.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Sample_Now.setObjectName("Label_Sample_Now")
        self.gridLayout.addWidget(self.Label_Sample_Now, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 850, 1871, 58))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Button_Pre_Sec = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Pre_Sec.sizePolicy().hasHeightForWidth())
        self.Button_Pre_Sec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Pre_Sec.setFont(font)
        self.Button_Pre_Sec.setObjectName("Button_Pre_Sec")
        self.gridLayout_3.addWidget(self.Button_Pre_Sec, 0, 2, 1, 1)
        self.Button_Start = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Start.sizePolicy().hasHeightForWidth())
        self.Button_Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Start.setFont(font)
        self.Button_Start.setObjectName("Button_Start")
        self.gridLayout_3.addWidget(self.Button_Start, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximum(64)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 0, 4, 1, 1)
        self.Button_End = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_End.sizePolicy().hasHeightForWidth())
        self.Button_End.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_End.setFont(font)
        self.Button_End.setObjectName("Button_End")
        self.gridLayout_3.addWidget(self.Button_End, 0, 1, 1, 1)
        self.Button_Nex_Sec = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Nex_Sec.sizePolicy().hasHeightForWidth())
        self.Button_Nex_Sec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Nex_Sec.setFont(font)
        self.Button_Nex_Sec.setObjectName("Button_Nex_Sec")
        self.gridLayout_3.addWidget(self.Button_Nex_Sec, 0, 3, 1, 1)
        self.Initial_Time_Label = QtWidgets.QLabel(self.centralwidget)
        self.Initial_Time_Label.setGeometry(QtCore.QRect(770, 870, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Initial_Time_Label.sizePolicy().hasHeightForWidth())
        self.Initial_Time_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Initial_Time_Label.setFont(font)
        self.Initial_Time_Label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Initial_Time_Label.setObjectName("Initial_Time_Label")
        self.End_Time_Label = QtWidgets.QLabel(self.centralwidget)
        self.End_Time_Label.setGeometry(QtCore.QRect(1810, 870, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.End_Time_Label.sizePolicy().hasHeightForWidth())
        self.End_Time_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.End_Time_Label.setFont(font)
        self.End_Time_Label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.End_Time_Label.setObjectName("End_Time_Label")
        self.Slider_Time_Label = QtWidgets.QLabel(self.centralwidget)
        self.Slider_Time_Label.setGeometry(QtCore.QRect(1300, 870, 91, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_Time_Label.sizePolicy().hasHeightForWidth())
        self.Slider_Time_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Slider_Time_Label.setFont(font)
        self.Slider_Time_Label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Slider_Time_Label.setObjectName("Slider_Time_Label")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(12, 12, 1871, 191))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Button_PreviousFile = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_PreviousFile.sizePolicy().hasHeightForWidth())
        self.Button_PreviousFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_PreviousFile.setFont(font)
        self.Button_PreviousFile.setObjectName("Button_PreviousFile")
        self.gridLayout_4.addWidget(self.Button_PreviousFile, 0, 0, 1, 1)
        self.Button_NextFile = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_NextFile.sizePolicy().hasHeightForWidth())
        self.Button_NextFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.Button_NextFile.setFont(font)
        self.Button_NextFile.setObjectName("Button_NextFile")
        self.gridLayout_4.addWidget(self.Button_NextFile, 0, 2, 1, 1)
        self.Label_SampleType = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_SampleType.sizePolicy().hasHeightForWidth())
        self.Label_SampleType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_SampleType.setFont(font)
        self.Label_SampleType.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_SampleType.setObjectName("Label_SampleType")
        self.gridLayout_4.addWidget(self.Label_SampleType, 0, 3, 1, 1)
        self.LineEdit_SampleType = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_SampleType.sizePolicy().hasHeightForWidth())
        self.LineEdit_SampleType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_SampleType.setFont(font)
        self.LineEdit_SampleType.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_SampleType.setObjectName("LineEdit_SampleType")
        self.gridLayout_4.addWidget(self.LineEdit_SampleType, 0, 4, 1, 1)
        self.Label_SampleIndex = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_SampleIndex.setFont(font)
        self.Label_SampleIndex.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_SampleIndex.setObjectName("Label_SampleIndex")
        self.gridLayout_4.addWidget(self.Label_SampleIndex, 0, 5, 1, 1)
        self.LineEdit_SampleIndex = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_SampleIndex.sizePolicy().hasHeightForWidth())
        self.LineEdit_SampleIndex.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_SampleIndex.setFont(font)
        self.LineEdit_SampleIndex.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_SampleIndex.setObjectName("LineEdit_SampleIndex")
        self.gridLayout_4.addWidget(self.LineEdit_SampleIndex, 0, 6, 1, 1)
        self.Select_Mold_ComboBox = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Select_Mold_ComboBox.sizePolicy().hasHeightForWidth())
        self.Select_Mold_ComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Select_Mold_ComboBox.setFont(font)
        self.Select_Mold_ComboBox.setObjectName("Select_Mold_ComboBox")
        self.Select_Mold_ComboBox.addItem("")
        self.Select_Mold_ComboBox.addItem("")
        self.Select_Mold_ComboBox.addItem("")
        self.Select_Mold_ComboBox.addItem("")
        self.gridLayout_4.addWidget(self.Select_Mold_ComboBox, 0, 7, 1, 1)
        self.LineEdit_Year = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Year.sizePolicy().hasHeightForWidth())
        self.LineEdit_Year.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Year.setFont(font)
        self.LineEdit_Year.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Year.setObjectName("LineEdit_Year")
        self.gridLayout_4.addWidget(self.LineEdit_Year, 1, 0, 1, 1)
        self.Label_Year = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Year.setFont(font)
        self.Label_Year.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Year.setObjectName("Label_Year")
        self.gridLayout_4.addWidget(self.Label_Year, 1, 1, 1, 1)
        self.LineEdit_Month = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Month.sizePolicy().hasHeightForWidth())
        self.LineEdit_Month.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Month.setFont(font)
        self.LineEdit_Month.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Month.setObjectName("LineEdit_Month")
        self.gridLayout_4.addWidget(self.LineEdit_Month, 1, 2, 1, 1)
        self.Label_Month = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Month.setFont(font)
        self.Label_Month.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Month.setObjectName("Label_Month")
        self.gridLayout_4.addWidget(self.Label_Month, 1, 3, 1, 1)
        self.LineEdit_Day = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Day.sizePolicy().hasHeightForWidth())
        self.LineEdit_Day.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Day.setFont(font)
        self.LineEdit_Day.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Day.setObjectName("LineEdit_Day")
        self.gridLayout_4.addWidget(self.LineEdit_Day, 1, 4, 1, 1)
        self.Label_Day = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Day.setFont(font)
        self.Label_Day.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Day.setObjectName("Label_Day")
        self.gridLayout_4.addWidget(self.Label_Day, 1, 5, 1, 1)
        self.LineEdit_Switch = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Switch.sizePolicy().hasHeightForWidth())
        self.LineEdit_Switch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Switch.setFont(font)
        self.LineEdit_Switch.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Switch.setObjectName("LineEdit_Switch")
        self.gridLayout_4.addWidget(self.LineEdit_Switch, 1, 6, 1, 1)
        self.LineEdit_Hour = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Hour.sizePolicy().hasHeightForWidth())
        self.LineEdit_Hour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Hour.setFont(font)
        self.LineEdit_Hour.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Hour.setObjectName("LineEdit_Hour")
        self.gridLayout_4.addWidget(self.LineEdit_Hour, 2, 0, 1, 1)
        self.Label_Hour = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Hour.setFont(font)
        self.Label_Hour.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Hour.setObjectName("Label_Hour")
        self.gridLayout_4.addWidget(self.Label_Hour, 2, 1, 1, 1)
        self.LineEdit_Minute = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Minute.sizePolicy().hasHeightForWidth())
        self.LineEdit_Minute.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Minute.setFont(font)
        self.LineEdit_Minute.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Minute.setObjectName("LineEdit_Minute")
        self.gridLayout_4.addWidget(self.LineEdit_Minute, 2, 2, 1, 1)
        self.Label_Minute = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Minute.setFont(font)
        self.Label_Minute.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Minute.setObjectName("Label_Minute")
        self.gridLayout_4.addWidget(self.Label_Minute, 2, 3, 1, 1)
        self.LineEdit_Second = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_Second.sizePolicy().hasHeightForWidth())
        self.LineEdit_Second.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.LineEdit_Second.setFont(font)
        self.LineEdit_Second.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Second.setObjectName("LineEdit_Second")
        self.gridLayout_4.addWidget(self.LineEdit_Second, 2, 4, 1, 1)
        self.Label_Second = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Second.setFont(font)
        self.Label_Second.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Second.setObjectName("Label_Second")
        self.gridLayout_4.addWidget(self.Label_Second, 2, 5, 1, 1)
        self.Button_Load_Switch = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Load_Switch.sizePolicy().hasHeightForWidth())
        self.Button_Load_Switch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Load_Switch.setFont(font)
        self.Button_Load_Switch.setObjectName("Button_Load_Switch")
        self.gridLayout_4.addWidget(self.Button_Load_Switch, 2, 6, 1, 1)
        self.Button_ChooseFile = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_ChooseFile.sizePolicy().hasHeightForWidth())
        self.Button_ChooseFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ChooseFile.setFont(font)
        self.Button_ChooseFile.setObjectName("Button_ChooseFile")
        self.gridLayout_4.addWidget(self.Button_ChooseFile, 2, 7, 2, 1)
        self.LineEdit_FileInformation = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_FileInformation.sizePolicy().hasHeightForWidth())
        self.LineEdit_FileInformation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LineEdit_FileInformation.setFont(font)
        self.LineEdit_FileInformation.setObjectName("LineEdit_FileInformation")
        self.gridLayout_4.addWidget(self.LineEdit_FileInformation, 3, 0, 1, 7)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_Save_Image = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Save_Image.sizePolicy().hasHeightForWidth())
        self.Button_Save_Image.setSizePolicy(sizePolicy)
        self.Button_Save_Image.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Save_Image.setFont(font)
        self.Button_Save_Image.setObjectName("Button_Save_Image")
        self.gridLayout_2.addWidget(self.Button_Save_Image, 0, 0, 1, 1)
        self.Button_Save_Feature = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Save_Feature.sizePolicy().hasHeightForWidth())
        self.Button_Save_Feature.setSizePolicy(sizePolicy)
        self.Button_Save_Feature.setSizeIncrement(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Save_Feature.setFont(font)
        self.Button_Save_Feature.setObjectName("Button_Save_Feature")
        self.gridLayout_2.addWidget(self.Button_Save_Feature, 0, 1, 1, 1)
        self.Button_Add_New_Feature = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Add_New_Feature.sizePolicy().hasHeightForWidth())
        self.Button_Add_New_Feature.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Add_New_Feature.setFont(font)
        self.Button_Add_New_Feature.setObjectName("Button_Add_New_Feature")
        self.gridLayout_2.addWidget(self.Button_Add_New_Feature, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量输出图像"))
        self.toolButton_Sample_Information.setText(_translate("MainWindow", "样本信息汇总"))
        self.Label_Sample_Now.setText(_translate("MainWindow", "显示当前样本信息"))
        self.Button_Pre_Sec.setText(_translate("MainWindow", "前一秒"))
        self.Button_Start.setText(_translate("MainWindow", "开始"))
        self.Button_End.setText(_translate("MainWindow", "结束"))
        self.Button_Nex_Sec.setText(_translate("MainWindow", "后一秒"))
        self.Initial_Time_Label.setText(_translate("MainWindow", "初始时刻"))
        self.End_Time_Label.setText(_translate("MainWindow", "结束时刻"))
        self.Slider_Time_Label.setText(_translate("MainWindow", "滑块时刻"))
        self.Button_PreviousFile.setText(_translate("MainWindow", "上一个文件"))
        self.Button_NextFile.setText(_translate("MainWindow", "下一个文件"))
        self.Label_SampleType.setText(_translate("MainWindow", "类型"))
        self.Label_SampleIndex.setText(_translate("MainWindow", "序号"))
        self.Select_Mold_ComboBox.setCurrentText(_translate("MainWindow", "       外弧宽面Tv"))
        self.Select_Mold_ComboBox.setItemText(0, _translate("MainWindow", "       外弧宽面Tv"))
        self.Select_Mold_ComboBox.setItemText(1, _translate("MainWindow", "       内弧宽面Tv"))
        self.Select_Mold_ComboBox.setItemText(2, _translate("MainWindow", "       右侧窄面Tv"))
        self.Select_Mold_ComboBox.setItemText(3, _translate("MainWindow", "       左侧窄面Tv"))
        self.Label_Year.setText(_translate("MainWindow", "年"))
        self.Label_Month.setText(_translate("MainWindow", "月"))
        self.Label_Day.setText(_translate("MainWindow", "日"))
        self.Label_Hour.setText(_translate("MainWindow", "时"))
        self.Label_Minute.setText(_translate("MainWindow", "分"))
        self.Label_Second.setText(_translate("MainWindow", "秒"))
        self.Button_Load_Switch.setText(_translate("MainWindow", "加载/跳转"))
        self.Button_ChooseFile.setText(_translate("MainWindow", "选择文件"))
        self.Button_Save_Image.setText(_translate("MainWindow", "保存图像"))
        self.Button_Save_Feature.setText(_translate("MainWindow", "保存特征"))
        self.Button_Add_New_Feature.setText(_translate("MainWindow", "添加新特征"))

